"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$directory$os$git_branch$git_status$nodejs$rust$golang$php $character"

[os]
disabled = false
format = "[$symbol](#blue) "

[os.symbols]
Fedora = "\uf30a"
Ubuntu = "󰕈"
Artix = "󰣇"
Arch = "󰣇"
CachyOS = "󰣇"
Macos = "\uf179"

[directory]
format = "[$path](cyan) "
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = "\uf126"
format = "[$symbol $branch](bold purple) "

[git_status]
format = "($ahead_behind$staged$modified$untracked$deleted$conflicted)"
ahead = "[\u21e1$count ](bold cyan)"
behind = "[\u21e3$count ](bold cyan)"
diverged = "[\u21e1$ahead_count\u21e3$behind_count ](bold cyan)"
staged = "[+$count ](bold green)"
modified = "[\u25cf$count ](bold yellow)"
untracked = "[?$count ](bold white)"
deleted = "[\u2718$count ](bold red)"
conflicted = "[\u26a1$count ](bold red)"

[nodejs]
symbol = ""
format = "[$symbol $version](green) "

[rust]
symbol = ""
format = "[$symbol $version](red) "

[golang]
symbol = ""
format = "[$symbol $version](cyan) "

[php]
symbol = ""
format = "[$symbol $version](purple) "

[character]
success_symbol = "[\u276f](green)"
error_symbol = "[\u276f](red)"
vimcmd_symbol = "[\u276e](blue)"
