# rEFInd-Regular-Dark
# Modified by iammrmehedi.

# Icons
icons_dir themes/rEFInd-Regular-Dark/icons

# Icon size
big_icon_size 128
small_icon_size 48

# Background image
banner themes/rEFInd-Regular-Dark/icons/bg_dark.png

# Selection image
selection_big themes/rEFInd-Regular-Dark/icons/selection_dark-big.png
selection_small themes/rEFInd-Regular-Dark/icons/selection_dark-small.png

# Tools
showtools reboot, shutdown, hidden_tags
hideui singleuser,hints

# Font
font themes/rEFInd-Regular-Dark/fonts/source-code-pro-extralight-14.png
