ARG BASE_IMAGE=ghcr.io/declarative-dale/purplefin
ARG BASE_TAG=base-generic-x86_64
FROM ${BASE_IMAGE}:${BASE_TAG}

# Packages required by image-builder's bootc-installer output and by Purplefin's
# online source-selection helper.
RUN dnf5 -y install \
      anaconda anaconda-install-env-deps anaconda-dracut \
      dracut-config-generic dracut-network net-tools squashfs-tools \
      grub2-efi-x64-cdboot python3-mako lorax-templates-x86 \
      biosdevname prefixdevname cosign skopeo && \
    dnf5 clean all && \
    mkdir -p /boot/efi /var/mnt && \
    cp -ra /usr/lib/efi/*/*/EFI /boot/efi

COPY installer/root/ /
COPY installer/catalog.tsv /usr/share/purplefin-installer/catalog.tsv
RUN chmod 0755 /usr/libexec/purplefin-installer/select-image
